<div id="navigation">
    <div class="text-center">
        <a href="#">

        </a>
    </div>
</div>
<style>
    /*the container must be positioned relative:*/
.autocomplete {
  position: relative;
  display: inline-block;
}



.autocomplete-items {
  position: absolute;
  border: 1px solid #d4d4d4;
  border-bottom: none;
  border-top: none;
  z-index: 99;
  /*position the autocomplete items to be the same width as the container:*/
  top: 100%;
  left: 0;
  right: 0;
}

.autocomplete-items div {
  padding: 10px;
  cursor: pointer;
  background-color: #fff; 
  border-bottom: 1px solid #d4d4d4; 
}

/*when hovering an item:*/
.autocomplete-items div:hover {
  background-color: #e9e9e9; 
}

/*when navigating through the items using the arrow keys:*/
.autocomplete-active {
  background-color: DodgerBlue !important; 
  color: #ffffff; 
}

</style>
<section id="search-bar">
                <div class="form-group">
                    <div class="autocomplete">
                        <input id="institute" class="form-control" style="width: 300px" type="search" name="city" placeholder="Branch">
                    </div>
                </div>
</section>
<!-- Student Background -->
<!-- Level of the Students -->
<!-- Cource of the student -->
<!-- Droup Down only program engineer, farmasy -->
<!-- Diploma (Politechnique), UG and PG(Post Graduate) -->
<!-- Student interested area cource or branch -->

<script>
    function autocomplete(inp, arr) {
        /*the autocomplete function takes two arguments,
        the text field element and an array of possible autocompleted values:*/
        var currentFocus;
        /*execute a function when someone writes in the text field:*/
        inp.addEventListener("input", function(e) {
            var a, b, i, val = this.value;
            /*close any already open lists of autocompleted values*/
            closeAllLists();
            if (!val) {
                return false;
            }
            currentFocus = -1;
            /*create a DIV element that will contain the items (values):*/
            a = document.createElement("DIV");
            a.setAttribute("id", this.id + "autocomplete-list");
            a.setAttribute("class", "autocomplete-items");
            /*append the DIV element as a child of the autocomplete container:*/
            this.parentNode.appendChild(a);
            /*for each item in the array...*/
            for (i = 0; i < arr.length; i++) {
                /*check if the item starts with the same letters as the text field value:*/
                if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                    /*create a DIV element for each matching element:*/
                    b = document.createElement("DIV");
                    /*make the matching letters bold:*/
                    b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
                    b.innerHTML += arr[i].substr(val.length);
                    /*insert a input field that will hold the current array item's value:*/
                    b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
                    /*execute a function when someone clicks on the item value (DIV element):*/
                    b.addEventListener("click", function(e) {
                        /*insert the value for the autocomplete text field:*/
                        inp.value = this.getElementsByTagName("input")[0].value;
                        /*close the list of autocompleted values,
                        (or any other open lists of autocompleted values:*/
                        closeAllLists();
                    });
                    a.appendChild(b);
                }
            }
        });
        /*execute a function presses a key on the keyboard:*/
        inp.addEventListener("keydown", function(e) {
            var x = document.getElementById('search_bar' + "autocomplete-list");
            if (x) x = x.getElementsByTagName("div");
            if (e.keyCode == 40) {
                /*If the arrow DOWN key is pressed,
                increase the currentFocus variable:*/
                currentFocus++;
                /*and and make the current item more visible:*/
                addActive(x);
            } else if (e.keyCode == 38) { //up
                /*If the arrow UP key is pressed,
                decrease the currentFocus variable:*/
                currentFocus--;
                /*and and make the current item more visible:*/
                addActive(x);
            } else if (e.keyCode == 13) {
                /*If the ENTER key is pressed, prevent the form from being submitted,*/
                e.preventDefault();
                if (currentFocus > -1) {
                    /*and simulate a click on the "active" item:*/
                    if (x) x[currentFocus].click();
                }
            }
        });

        function addActive(x) {
            /*a function to classify an item as "active":*/
            if (!x) return false;
            /*start by removing the "active" class on all items:*/
            removeActive(x);
            if (currentFocus >= x.length) currentFocus = 0;
            if (currentFocus < 0) currentFocus = (x.length - 1);
            /*add class "autocomplete-active":*/
            x[currentFocus].classList.add("autocomplete-active");
        }

        function removeActive(x) {
            /*a function to remove the "active" class from all autocomplete items:*/
            for (var i = 0; i < x.length; i++) {
                x[i].classList.remove("autocomplete-active");
            }
        }

        function closeAllLists(elmnt) {
            /*close all autocomplete lists in the document,
            except the one passed as an argument:*/
            var x = document.getElementsByClassName("autocomplete-items");
            for (var i = 0; i < x.length; i++) {
                if (elmnt != x[i] && elmnt != inp) {
                    x[i].parentNode.removeChild(x[i]);
                }
            }
        }
        /*execute a function when someone clicks in the document:*/
        document.addEventListener("click", function(e) {
            closeAllLists(e.target);
        });
    }
    // Data in array
    var countries = [
		'3-D Animation and Graphics', 
		'Administration Services', 
		'Advanced   Electronics   and   Communication Engineering', 
		'Aero Space Engineering', 
		'Aeronautical Engineering', 
		'Agricultural Engineering', 
		'Agricultural Technology', 
		'Agriculture Engineering', 
		'Aircraft Maintenance Engineering', 
		'Aircraft Maintenance Engineering (Avionics)', 
		'Aircraft Maintenance Engineering (Helicopter and Power Plants)', 
		'Animation and Multimedia Technology', 
		'Apparel Design and Fabric', 
		'Apparel Design and Fabrication Technology', 
		'Apparel Design and Fashion Technology', 
		'Apparel Manufacture and Design', 
		'Apparel Technology', 
		'Applied Electronics', 
		'Applied Electronics and instrumentation Engineering', 
		'Applied Videography', 
		'Armament Engineering', 
		'Armament Engineering (Gun Fitter)', 
		'Artificer Training (Electrical)', 
		'Artificer Training (Electronics)', 
		'Artificer Training (Mechanical)', 
		'Audiography and Sound Engineering', 
		'Automation and Robotics', 
		'Automobile Engineering', 
		'Automobile Engineering (Automobile Fitter)', 
		'Automotive Engineering', 
		'Beauty and Hair Dressing', 
		'Beauty Culture and Cosmetology', 
		'Biomedical Electronics', 
		'Biomedical Engineering', 
		'Biomedical instrumentation', 
		'Biotechnology', 
		'CAD CAM', 
		'Campus Wide Network Design and Maintenance', 
		'Carpet Technology', 
		'CDDM', 
		'Cement Technology', 
		'Ceramic Engineering and Technology', 
		'Ceramic Technology', 
		'Ceramics', 
		'Ceramics Engineering', 
		'Chemical Engineering', 
		'Chemical Engineering (Fertilizer)', 
		'Chemical Engineering (Oil Technology)', 
		'Chemical Engineering (Petro Chemical)', 
		'Chemical Engineering (Petrochemical)', 
		'Chemical Engineering (Plastic and Polymer)', 
		'Chemical Engineering (Sugar Technology)', 
		'Chemical Engineering Specialization inPetrochemicals', 
		'Chemical Technology', 
		'Chemical Technology (Paint Technology)', 
		'Chemical   Technology   (Rubber   and   Plastic Technology)', 
		'Chemical Technology (Rubber/ Plastic)', 
		'Chemical Technology Fertilizer', 
		'Cinematography', 
		'Civil (Construction)', 
		'Civil (Public Health and Environment) Engineering', 
		'Civil and Environmental Engineering', 
		'Civil and Rural Engineering', 
		'Civil Draftsman', 
		'Civil Engineering', 
		'Civil Engineering (Construction Technology)', 
		'Civil Engineering (Environment and Pollution Control)', 
		'Civil Engineering (Environmental and Pollution Control)', 
		'Civil Engineering (Environmental Engineering)', 
		'Civil Engineering (Public Health Engineering)', 
		'Civil Engineering (Rural Engineering)', 
		'Civil Engineering and Planning', 
		'Civil  Engineering  Environment  and  Pollution Control', 
		'Civil Environmental Engineering', 
		'Civil Technology', 
		'Combat Armament and Weapon Technology', 
		'Combat Driving and Maintenance Technology', 
		'Combat Radio and Communication Technology', 
		'Commercial and Computer Practice', 
		'Commercial Practice', 
		'Commercial Practice (KAN and ENG)', 
		'Computer  Aided  Costume  Design  and  Dress Making', 
		'Computer and information Science', 
		'Computer Application and Business Management', 
		'Computer Applications', 
		'Computer Engineering', 
		'Computer Engineering and Application', 
		'Computer Hardware and Maintenance', 
		'Computer Hardware and Networking', 
		'Computer Hardware Engineering', 
		'Computer Hardware Maintenance', 
		'Computer Networking', 
		'Computer Science', 
		'Computer Science and Engineering', 
		'Computer Science and information Technology', 
		'Computer Science and Technology', 
		'Computer Software Technology', 
		'Computer Technology', 
		'Computer Technology and Applications', 
		'Construction Engineering', 
		'Construction Technology', 
		'Construction Technology and Management', 
		'Control and instrumentation', 
		'Cosmetology and Health', 
		'Costumer Design and Dress Making', 
		'Cyber Forensics and information Security', 
		'Dairy Engineering', 
		'Design and Drafting Technology', 
		'Digital Electronics', 
		'Digital Electronics and Communication Engineering', 
		'Digital Electronics and Microprocessor', 
		'Digital Systems', 
		'Direction Screen Play Writing and TV Production', 
		'Dress Designing and Garment Manufacturing', 
		'Drilling Engineering', 
		'Drilling Technology', 
		'ECG Technology', 
		'Electrical and Electronics (Power System)', 
		'Electrical and Electronics Engineering', 
		'Electrical and instrumentation Engineering', 
		'Electrical and Mechanical Engineering', 
		'Electrical Engineering', 
		'Electrical Engineering (Electronics and Power)', 
		'Electrical Engineering (Industrial Control)', 
		'Electrical   Engineering   (Instrumentation   and Control)', 
		'Electrical Engineering industrial Control', 
		'Electrical Power System', 
		'Electrical Power Systems', 
		'Electronic instrumentation and Control Engineering', 
		'Electronic Science and Engineering', 
		'Electronics Engineering', 
		'Electronics (Fiber Optics)', 
		'Electronics (Robotics)', 
		'Electronics and Avionics', 
		'Electronics and Communication Engineering', 
		'Electronics  and  Communication  Engineering (Industry Integrated)', 
		'Electronics  and  Communication  Engineering (Microwaves)', 
		'Electronics and Communication Technology', 
		'Electronics and Communications Engineering', 
		'Electronics and Computer Engineering', 
		'Electronics and Electrical Engineering', 
		'Electronics and instrumentation Engineering', 
		'Electronics and Production', 
		'Electronics and Telecommunication', 
		'Electronics and Telecommunication Engineering', 
		'Electronics and Tele-Communication Engineering', 
		'Electronics and Telecommunication Engineering (Radio and System)', 
		'Electronics and Telecommunication Engineering (Technologynician Electronic Radio)', 
		'Electronics and Telecommunications Engineering', 
		'Electronics and Video Engineering', 
		'Electronics Communication and instrumentation Engineering', 
		'Electronics Engineering', 
		'Electronics Engineering (Digital Electronics)', 
		'Electronics Engineering (Industry integrated)', 
		'Electronics Engineering (Micro Electronics)', 
		'Electronics Engineering (Specialization in Consumer Electronics)', 
		'Electronics   Engineering   Modern   Consumer Electronics', 
		'Electronics Engineering with Microprocessor', 
		'Electronics instrument and Control', 
		'Electronics instrumentation and Control Engineering', 
		'Electronics Production and Maintenance', 
		'Electronics Robotics', 
		'Electronics Technology', 
		'Electronics Tele Communication', 
		'Embedded Systems', 
		'Engineering Education', 
		'Environmental Engineering', 
		'Fabrication Technology', 
		'Fabrication Technology and Erection Engineering', 
		'Fabrication Technology and Erection Engineering', 
		'Fashion and Apparel Design', 
		'Fashion and Clothing Technology', 
		'Fashion and Design', 
		'Fashion Designing', 
		'Fashion Designing and Garment Technology', 
		'Fashion Technology', 
		'Film and Video Editing', 
		'Film Editing and TV Production', 
		'Film Technology (Animation and Visual Effects', 
		'Film Technology and TV Production (Cinematography)', 
		'Film  Technology  and  TV  Production  (Digital intermediate)', 
		'Film   Technology   and   TV   Production   (Film Processing)', 
		'Film  Technology  and  TV  Production  (Sound Recording and Sound Engineering)', 
		'Finance Account and Auditing', 
		'Fire Technology and Safety', 
		'Fisheries Technology', 
		'Food Processing and Preservation', 
		'Food Processing Technology', 
		'Food Technology', 
		'Footwear Technology', 
		'Foundry Technology', 
		'Garment and Fashion Technology', 
		'Garment Design and Fashion Technology', 
		'Garment Fabrication', 
		'Garment Manufacturing Technology', 
		'Garment Technology', 
		'Geographic  information  System  (G.I.S.)  and Global Positioning System', 
		'Geoinformatics', 
		'Glass and Ceramics Engineering', 
		'Handloom and Textile Technology', 
		'Heat Power Engineering', 
		'Home Science', 
		'Hotel Management and Catering Technology', 
		'Industrial and Production Engineering', 
		'Industrial Electronics', 
		'Industrial Production Engineering', 
		'Information and Communication Technology', 
		'Information Engineering', 
		'Information Science', 
		'Information Science and Engineering', 
		'Information Science and Technology', 
		'Information Technology', 
		'Information Technology and Engineering', 
		'Information Technology Enabled Services and Management', 
		'Instrument Technology', 
		'Instrumentation and Control Engineering', 
		'Instrumentation and Process Control', 
		'Instrumentation Engineering', 
		'Instrumentation Technology', 
		'Instruments and Medical Equipment', 
		'Interior Decoration', 
		'Interior Design', 
		'Jewellery Design and Manufacture Technology', 
		'Knitting and Garment Technology', 
		'Knitting Technology', 
		'Leather and Fashion Technology', 
		'Leather Goods and Footwear Tech', 
		'Leather Technology', 
		'Leather Technology Footwear Computer Aided Shoe Design', 
		'Leather Technology Tanning', 
		'Library and information Science', 
		'Machine Engineering', 
		'Machine Tools and Maintenance Engineering', 
		'Machine Tools Technology', 
		'Maintenance Engineering', 
		'Manufacturing Engineering', 
		'Manufacturing Technology', 
		'Marine Engineering', 
		'Marine Engineering and Systems', 
		'Marine   Engineering   and   Systems   (Artificer Training)', 
		'Mass Communication', 
		'Material Management', 
		'Mechanical CAD/CAM', 
		'Mechanical Engineering', 
		'Mechanical Engineering ( Production)', 
		'Mechanical Engineering (Automobile)', 
		'Mechanical Engineering (CAD/CAM)', 
		'Mechanical Engineering (Foundry)', 
		'Mechanical Engineering (Industry Integrated)', 
		'Mechanical Engineering (Machine Tool Maintenance and Repairs)', 
		'Mechanical Engineering (Maintenance)', 
		'Mechanical Engineering (Refrigeration and Air Conditioning)', 
		'Mechanical Engineering (Repair and Maintenance)', 
		'Mechanical Engineering (Tool and Die)', 
		'Mechanical Engineering Automobile', 
		'Mechanical Engineering Power Plant Engineering', 
		'Mechanical Engineering Production', 
		'Mechanical Engineering', 'Refrigeration and Air Conditioning', 
		'Mechanical Engineering (CAD)', 
		'Mechanical Engineering Tool Engineering', 
		'Mechanical Engineering Tube Well Engineering', 
		'Mechanical Welding and Sheet Metal', 
		'Mechanical Welding and Sheet Metal Engineering', 
		'Mechanical Engineering Computer Aided Design/Computer Aided Manufacturing', 
		'Mechatronics', 
		'Medical Electronics Engineering', 
		'Medical Laboratory Technology', 
		'Metallurgical Engineering', 
		'Metallurgy', 
		'Metallurgy and Material Technology', 
		'Micro Electronics', 
		'Mine Engineering', 
		'Mine Surveying', 
		'Mining and Mine Surveying', 
		'Mining Engineering', 
		'Multimedia Technology', 
		'Navy Entry Artificer/ Diploma in Mechanical and Electrical', 
		'Network Engineering', 
		'Office Management and Computer Application', 
		'Ophthalmic Technology', 
		'Opto-Electronics Engineering', 
		'Packaging Technology', 
		'Paint Technology', 
		'Paper Technology', 
		'Paper and Pulp Technology', 
		'Petrochemical Engineering', 
		'Petrochemical Refinery', 
		'Petrochemical Technology', 
		'Petroleum Engineering', 
		'Petroleum Technology', 
		'Photography', 
		'Plastic and Mould Technology', 
		'Plastic and Polymer Engineering', 
		'Plastic Engineering', 
		'Plastic Mould Technology', 
		'Plastic Technology', 
		'Plastics Engineering', 
		'Plastics Mould Technology', 
		'Plastics Processing and Testing', 
		'Plastics Technology', 
		'Polymer Technology', 
		'Post Plastic Mould Design', 
		'Post Plastic Process and Testing', 
		'Power Electronics', 
		'Power Systems Engineering', 
		'Precision Manufacturing', 
		'Printing and Packing Technology', 
		'Printing Technology', 
		'Production and Industrial Engineering', 
		'Production Engineering', 
		'Production Technology', 
		'Pulp Technology', 
		'Quantity Surveying and Construction Management', 
		'Refrigeration and Air Conditioning', 
		'Renewable Energy', 
		'Robotics and Mechatronics', 
		'Rubber Technology', 
		'Saddlery Technology and Export Management', 
		'Shipbuilding Engineering', 
		'Small Arms Engineering', 
		'Sound Recording and Engineering', 
		'Sugar Technology', 
		'Surface Coating Technology', 
		'Survey Engineering', 
		'Technical Chemistry', 
		'Technician X-Ray Technology', 
		'Telecommunication Engineering', 
		'Telecommunication Technology', 
		'Textile Chemistry', 
		'Textile Design', 
		'Textile Designing', 
		'Textile Designing Printing', 
		'Textile Engineering', 
		'Textile Manufactures', 
		'Textile Manufacturing and Technology', 
		'Textile Manufacturing Technology', 
		'Textile Marketing and Management', 
		'Textile Processing', 
		'Textile Processing Technology', 
		'Textile Technology', 
		'Textile Technology (Manmade Fibre)', 
		'Textile Technology (Textile Design and Weaving)', 
		'Tool and Die Engineering', 
		'Tool and Die Making', 
		'Tool Die and Mould Making', 
		'Transportation Engineering', 
		'Transportation Engineering and Management', 
		'Travel and Tourism', 
		'TV and Sound Engineering', 
		'Water Technology and Health Science', 
		'Weapons Engineering', 
		'Web Designing', 
		'Wood and Paper Technology', 
		'Wood Technology',
		'Advanced Die and Mould Making', 
		'Advanced Electrical Power System', 
		'Advanced   Electronics   and   Communication', 
		'Engineering', 
		'Advanced Mechatronics and Industrial', 
		'Automation', 
		'Advanced Refrigeration and Air Conditioning', 
		'Automobile Engineering', 
		'Biotechnology Tissue Culture', 
		'CAD/CAM', 
		'Computer Aided Design and Manufacture', 
		'Computer   Aided   Design   Manufacture   and', 
		'Engineering', 
		'Computer Applications', 
		'Computer Hardware and Networking', 
		'Computer Hardware Maintenance and', 
		'Networking', 
		'Electrical Engineering', 
		'Electronics Communication and', 
		'Instrumentation Engineering', 
		'Environmental Engineering', 
		'Fire Technology and Safety', 
		'Food Technology', 
		'Forge Technology', 
		'Foundry Technology', 
		'Geographic  information  System  (G.I.S.)  and', 
		'Global Positioning System', 
		'Industrial Safety', 
		'Industrial Safety and Engineering', 
		'Information Technology', 
		'Knitting and Garment Technology', 
		'Mechanical Engineering', 
		'Medical Electronics', 
		'Petrochemical Engineering', 
		'Plant Engineering', 
		'Plastic Mould Design', 
		'Plastic Mould Design (CAD/CAM)', 
		'Plastic Mould Technology', 
		'Plastic Technology', 
		'Plastics Processing and Testing', 
		'Polymer Science and Rubber Technology', 
		'Post Plastic Mould Design', 
		'Post Plastic Process and Testing', 
		'Power Plant Engineering and Energy', 
		'Management', 
		'Production Engineering System Technology', 
		'Refrigeration and Air Conditioning', 
		'Rubber Technology', 
		'Software Testing', 
		'Textile Processing', 
		'Thermal Power Engineering', 
		'Tool and Die Engineering', 
		'Tool Design', 
		'Town Planning and Architecture', 
		'Web Designing',
		'3-D Animation and Graphics', 
		'Advanced Mechatronics and industrial', 
		'Automation', 
		'Aero Space Engineering', 
		'Aeronautical Engineering', 
		'Aerospace Engineering', 
		'Agricultural Engineering', 
		'Agricultural Technology', 
		'Agriculture Engineering', 
		'Aircraft Maintenance Engineering', 
		'Airline Management', 
		'Apparel and Production Management', 
		'Applied Electronics and Communications', 
		'Applied Electronics and instrumentation', 
		'Engineering', 
		'Architectural Assistantship', 
		'Architecture and Interior Decoration', 
		'Artificial Intelligence and Data Science', 
		'Automation and Robotics', 
		'Automation Engineering', 
		'Automobile Engineering', 
		'Automobile Maintenance Engineering', 
		'Automotive Technology', 
		'Biochemical Engineering', 
		'Bioelectronics Engineering', 
		'Bioinformatics', 
		'Biomedical Engineering', 
		'Biomedical and Robotic Engineering', 
		'Biomedical instrumentation', 
		'Biotechnology', 
		'Biotechnology and Biochemical Engineering', 
		'Building and Construction Technology', 
		'Carpet and Textile Technology', 
		'Cement and Ceramic Technology', 
		'Ceramic Engineering and Technology', 
		'Ceramic Technology', 
		'Ceramics Engineering', 
		'Chemical Engineering (Desalination and Water', 
		'Treatment)', 
		'Chemical and Biochemical Engineering', 
		'Chemical and Electro Chemical Engineering', 
		'Chemical Engineering', 
		'Chemical Engineering (Plastic and Polymer)', 
		'Chemical Technology', 
		'Civil and Environmental Engineering', 
		'Civil and infrastructure Engineering', 
		'Civil and Rural Engineering', 
		'Civil and Water Management Engineering', 
		'Civil Engineering', 
		'Civil Engineering with Computer Application', 
		'Civil Engineering (Construction Technology)', 
		'Civil Engineering (Environmental Engineering)', 
		'Civil Engineering and Planning', 
		'Civil  Engineering  Environment  and  Pollution', 
		'Control', 
		'Civil Environmental Engineering', 
		'Civil Technology', 
		'Computer and Communication Engineering', 
		'Computer Engineering', 
		'Computer Engineering (Software Engineering)', 
		'Computer Engineering and Application', 
		'Computer Networking', 
		'Computer Science and Applied Mathematics', 
		'Computer Science and Biosciences', 
		'Computer Science and Business Systems', 
		'Computer   Science   and   Engineering   (Cyber', 
		'Security)', 
		'Computer Science and Design', 
		'Computer Science and Engineering', 
		'Computer  Science and  Engineering (Artificial', 
		'Intelligence )', 
		'Computer  Science and  Engineering (Artificial', 
		'Intelligence and Machine Learning)', 
		'Computer   Science   and   Engineering   (Data', 
		'Science)', 
		'Computer Science and Engineering (Internet of Things  and  Cyber  Security  Including  Block Chain Technology)', 
		'Computer Science and Engineering (IoT)', 
		'Computer Science and Engineering (Networks)', 
		'Computer Science and Engineering and Business', 
		'Systems', 
		'Computer Science and information Technology', 
		'Computer Science and Medical Engineering', 
		'Computer Science and Social Sciences', 
		'Computer Science and Systems Engineering', 
		'Computer Science and Technology', 
		'Computer Technology', 
		'Computing in Multimedia', 
		'Computing in Software', 
		'Construction Engineering', 
		'Construction Engineering and Management', 
		'Construction Technology', 
		'Construction Technology and Management', 
		'Cyber Physical Systems', 
		'Dairy Engineering', 
		'Dairy Technology', 
		'Digital Techniques For Design and Planning', 
		'Dyestuff Technology', 
		'Electrical and Computer Engineering', 
		'Electrical and Electronics (Power System)', 
		'Electrical and Electronics Engineering', 
		'Electrical and instrumentation Engineering', 
		'Electrical and Power Engineering', 
		'Electrical Engineering', 
		'Electrical Engineering (Electronics and Power)', 
		'Electrical instrumentation and Control', 
		'Engineering', 
		'Electrical Power Engineering', 
		'Electrical', 'Electronics and Power Engineering', 
		'Electronic Engineering', 
		'Electronic instrumentation and Control', 
		'Engineering', 
		'Electronic Science and Engineering', 
		'Electronics and Biomedical Engineering', 
		'Electronics and Communication', 
		'(Communication System Engineering)', 
		'Electronics and Communication Engineering', 
		'Electronics  and  Communication  Engineering', 
		'(Bio-Medical Engineering)', 
		'Electronics  and  Communication  Engineering', 
		'(Industry Integrated)', 
		'Electronics  and  Communication  Engineering', 
		'(Microwaves)', 
		'Electronics and Communication Technology', 
		'Electronics and Computer Engineering', 
		'Electronics and Computer Science', 
		'Electronics and Control Systems', 
		'Electronics and Electrical Engineering', 
		'Electronics and Instrumentation Engineering', 
		'Electronics and Power Engineering', 
		'Electronics and Telecommunication', 
		'Electronics and Telecommunication Engineering', 
		'Electronics and Tele-Communication', 
		'Engineering', 
		'Electronics and Telecommunication Engineering', 
		'(Technologynician Electronic Radio)', 
		'Electronics and Telecommunications', 
		'Engineering', 
		'Electronics and Telematics Engineering', 
		'Electronics Communication and', 
		'Instrumentation Engineering', 
		'Electronics Design Technology', 
		'Electronics Engineering', 
		'Electronics Instrument and Control', 
		'Electronics Instrumentation and Control', 
		'Engineering', 
		'Electronics System Engineering', 
		'Electronics Technology', 
		'Energy and Environmental Management', 
		'Energy Engineering', 
		'Environment Engineering', 
		'Environmental Engineering', 
		'Environmental Science and Engineering', 
		'Environmental Science and Technology', 
		'Facilities and Services Planning', 
		'Fashion and Apparel Engineering', 
		'Fashion Technology', 
		'Fibres and Textiles Processing Technology', 
		'Fire Engineering', 
		'Fire Technology and Safety', 
		'Fisheries Engineering', 
		'Food Engineering and Technology', 
		'Food Processing and Preservation', 
		'Food Processing Technology', 
		'Food Technology', 
		'Food Technology and Management', 
		'Footwear Technology', 
		'Geo informatics', 
		'Handloom and Textile Technology', 
		'Industrial and Production Engineering', 
		'Industrial Biotechnology', 
		'Industrial Engineering', 
		'Industrial Engineering and Management', 
		'Industrial Production Engineering', 
		'Information and Communication Technology', 
		'Information Engineering', 
		'Information Science and Engineering', 
		'Information Science and Technology', 
		'Information Technology', 
		'Information Technology and Engineering', 
		'Instrument Technology', 
		'Instrumentation and Control Engineering', 
		'Instrumentation and Electronics', 
		'Instrumentation Engineering', 
		'Instrumentation Technology', 
		'Jute and Fibre Technology', 
		'Leather Technology', 
		'Man Made Fibre Technology', 
		'Man-Made Textile Technology', 
		'Manufacturing Engineering', 
		'Manufacturing Engineering and Technology', 
		'Manufacturing Process and Automation', 
		'Engineering', 
		'Manufacturing Science and Engineering', 
		'Manufacturing Technology', 
		'Marine Engineering', 
		'Marine Technology', 
		'Material Science and Technology', 
		'Mechanical and Automation Engineering', 
		'Mechanical   and   Mechatronics   Engineering', 
		'(Additive Manufacturing)', 
		'Mechanical and Smart Manufacturing', 
		'Mechanical Engineering', 
		'Mechanical Engineering (Automobile)', 
		'Mechanical Engineering (Industry Integrated)', 
		'Mechanical Engineering (Manufacturing', 
		'Engineering)', 
		'Mechanical Engineering (Production)', 
		'Mechanical Engineering (Welding Technology)', 
		'Mechanical Engineering Automobile', 
		'Mechanical Engineering Design', 
		'Mechatronics Engineering', 
		'Medical Electronics Engineering', 
		'Medical Lab Technology', 
		'Metallurgical and Materials Engineering', 
		'Metallurgical Engineering', 
		'Metallurgy', 
		'Metallurgy and Material Technology', 
		'Mine Engineering', 
		'Mining Engineering', 
		'Nano Science and Technology', 
		'Nano Technology', 
		'Naval Architecture and Ship Building', 
		'Engineering', 
		'Nuclear Science and Technology', 
		'Oil and Paint Technology', 
		'Oil Technology', 
		'Oils', 'Oleochemicals and Surfactants Technology', 
		'Optics and Optoelectronics', 
		'Packaging Technology', 
		'Paint Technology', 
		'Petrochem and Petroleum Refinery Engineering', 
		'Petrochem Engineering', 
		'Petrochemical Engineering', 
		'Petrochemical Technology', 
		'Petroleum Engineering', 
		'Petroleum Technology', 
		'Pharmaceutical Engineering', 
		'Pharmaceuticals and Fine Chemical Technology', 
		'Pharmaceuticals Chemistry and Technology', 
		'Plastic and Polymer Engineering', 
		'Plastic Technology', 
		'Plastics Engineering', 
		'Polymer Engineering', 
		'Polymer Engineering and Technology', 
		'Polymer Science and Chemical Technology', 
		'Polymer Science and Technology', 
		'Polymer Technology', 
		'Poultry Technology', 
		'Power Electronics', 
		'Power Electronics and instrumentation', 
		'Engineering', 
		'Power Electronics Engineering', 
		'Power Engineering', 
		'Precision Manufacturing', 
		'Printing and Packing Technology', 
		'Printing Technology', 
		'Printing', 'Graphics and Packaging', 
		'Production and industrial Engineering', 
		'Production Engineering', 
		'Pulp Technology', 
		'Radio Physics and Electronics', 
		'Robotics and Automation', 
		'Rubber and Plastics Technology', 
		'Rubber Technology', 
		'Safety and Fire Engineering', 
		'Shipbuilding Engineering', 
		'Silk Technology', 
		'Software Engineering', 
		'Structural Engineering', 
		'Surface Coating Technology', 
		'Telecommunication Engineering', 
		'Textile Chemistry', 
		'Textile Engineering', 
		'Textile Plant Engineering', 
		'Textile Processing', 
		'Textile Technology', 
		'Tool Engineering',
		'Cement Technology', 
		'Chemical Engineering (Sugar Technology)', 
		'Computer Applications', 
		'Computer Engineering and Application', 
		'Computer Hardware and Networking', 
		'Food', 'Drug and Cosmetics', 
		'Industrial Engineering', 
		'Mechanical Engineering (Production)', 
		'Networking', 
		'Plastics Processing and Testing', 
		'Sugar Technology', 
		'Web Designing',
		'Advanced   Communication   and   information', 
		'System', 
		'Advanced Computer Aided Design', 
		'Advanced Design and Manufacturing', 
		'Advanced Electrical Power System', 
		'Advanced Electronics', 
		'Advanced   Electronics   and   Communication', 
		'Engineering', 
		'Advanced   Manufacturing   and   Mechanical', 
		'Systems Design', 
		'Advanced Manufacturing Systems', 
		'Advanced Manufacturing Technology', 
		'Advanced Materials Technology', 
		'Advanced Production Systems', 
		'Aero Dynamic Engineering', 
		'Aero Space Engineering', 
		'Aerospace Technology', 
		'Aeronautical Engineering', 
		'Agricultural Engineering', 
		'Agricultural Science and Technology', 
		'Air Armament', 
		'Apparel Technology', 
		'Applied Electronics', 
		'Applied Electronics and Communication System', 
		'Applied Electronics and Communications', 
		'Applied Electronics and instrumentation', 
		'Engineering', 
		'Applied instrumentation', 
		'Applied Mechanics', 
		'Armament Engineering (Gun Fitter)', 
		'Artificial intelligence', 
		'Artificial Intelligence and Data Science', 
		'Atmospheric Science', 
		'Automated Manufacturing Systems', 
		'Automation', 
		'Automation and Control Power Systems', 
		'Automation and Robotics', 
		'Automobile Engineering', 
		'Automobile Technology', 
		'Automotive Electronics', 
		'Automotive Engineering', 
		'Automotive Systems', 
		'Automotive Technology', 
		'Avionics', 
		'Aviation Technology', 
		'Bio Electronics', 
		'Biochemical Engineering', 
		'Biochemical Engineering and Biotechnology', 
		'Bioinformatics', 
		'Biomedical Electronics', 
		'Biomedical Engineering', 
		'Biomedical instrumentation', 
		'Biomedical Instrumentation and Signal', 
		'Processing', 
		'Biomedical Signal Processing and', 
		'instrumentation', 
		'Biometrics and Cyber Security', 
		'Bioprocess Engineering', 
		'Bioprocess Technology', 
		'Biotechnology', 
		'Biotechnology and Biochemical Engineering', 
		'Building Construction Technology', 
		'CAD/CAM', 
		'CAD/CAM Engineering', 
		'CAD/CAM/CAE', 
		'CAD/ CAM Robotics', 
		'Ceramic Engineering and Technology', 
		'Ceramics Engineering', 
		'Chemical and Biotechnology', 
		'Civil and Environmental Technology', 
		'Chemical Engineering', 
		'Chemical Processing in Textiles', 
		'Chemical Reaction Engineering', 
		'Chemical Science and Technology', 
		'Chemical Technology', 
		'Chemical Technology (Rubber/ Plastic)', 
		'Civil (Construction Engineering and', 
		'Management)', 
		'Civil (Public Health and Environment)', 
		'Engineering', 
		'Civil (Structural Engineering)', 
		'Civil (Water Resource Engineering)', 
		'Civil Engineering', 
		'Civil Engineering (Computer Aided Structural', 
		'Engineering)', 
		'Civil Engineering (Construction Technology)', 
		'Civil Engineering (Environmental and Pollution', 
		'Control)', 
		'Civil Engineering (Environmental Engineering)', 
		'Civil Engineering (Transportation Engineering)', 
		'Civil Engineering (Water Management)', 
		'Civil Environmental Engineering', 
		'Cloud Computing', 
		'Combat Equipment Technology', 
		'Combat Vehicles (Mechanical Engineering)', 
		'Communication and Information Systems', 
		'Communication and Networking', 
		'Communication and Signal Process', 
		'Communication Control and Networking', 
		'Communication Engineering', 
		'Communication Engineering and Signal', 
		'Processing', 
		'Communication Networks', 
		'Communication Systems', 
		'Communication Technology and Management', 
		'Communications Engineering', 
		'Computational Analysis in Mechanical Science', 
		'Computational Biology', 
		'Computational  Engineering  and  Networking', 
		'(Data Science)', 
		'Computational Mechanics', 
		'Computational Mechanics (Mechanical', 
		'Engineering)', 
		'Computer Aided Analysis and Design', 
		'Computer Aided Design', 
		'Computer Aided Design and Computer Aided', 
		'Manufacture', 
		'Computer Aided Design and Manufacture', 
		'Computer   Aided   Design   Manufacture   and', 
		'Automation', 
		'Computer   Aided   Design   Manufacture   and', 
		'Engineering', 
		'Computer Aided Design of Structures', 
		'Computer Aided Process Design', 
		'Computer Aided Structural Analysis and Design', 
		'Computer Aided Structural Engineering', 
		'Computer and Communication', 
		'Computer and Communication Engineering', 
		'Computer and information Science', 
		'Computer and Information Technology', 
		'Computer Applications', 
		'Computer Applications in Industrial Drives', 
		'Computer Cognition and Technology', 
		'Computer Engineering', 
		'Computer Engineering (Software Engineering)', 
		'Computer Engineering and Application', 
		'Computer Engineering and Networking', 
		'Computer Hardware and Networking', 
		'Computer integrated Manufacturing', 
		'Computer Network Engineering', 
		'Computer Networking', 
		'Computer Networking and Engineering', 
		'Computer Networks', 
		'Computer Networks and information Security', 
		'Computer Networks and internet Security', 
		'Computer Science', 
		'Computer Science and Engineering', 
		'Computer  Science and  Engineering (Artificial', 
		'Intelligence and Machine Learning)', 
		'Computer   Science   and   Engineering   (Cyber', 
		'Security)', 
		'Computer Science and Engineering (Networks)', 
		'Computer Science and Engineering (Operations', 
		'Research)', 
		'Computer Science and Information Security', 
		'Computer Science and Information System', 
		'Computer Science and Information Technology', 
		'Computer Science and Systems Engineering', 
		'Computer Science and Technology', 
		'Computer Systems and Technology', 
		'Computer   Science   Engineering   (Big   Data', 
		'Analytics)', 
		'Computer Technology', 
		'Computer Technology and Applications', 
		'Computer Vision and Image Processing', 
		'Computing in Computing', 
		'Construction and Project Management', 
		'Construction Engineering', 
		'Construction Engineering and Management', 
		'Construction Management', 
		'Construction Planning and Management', 
		'Construction Project Management', 
		'Construction Technology', 
		'Construction Technology and Management', 
		'Control and Instrument', 
		'Control and Instrumentation', 
		'Control Engineering', 
		'Control System Engineering', 
		'Control Systems', 
		'Cryogenic Engineering', 
		'Cyber Forensics', 
		'Cyber Forensics and information Security', 
		'Cyber Security', 
		'Cybersecurity Systems and Networks', 
		'Data Engineering', 
		'Data Sciences', 
		'Design and Production', 
		'Design and Thermal Engineering', 
		'Design Engineering', 
		'Design for Manufacturing', 
		'Design of Mechanical Equipment', 
		'Design of Mechanical Systems', 
		'Digital Communication', 
		'Digital Communication Engineering', 
		'Digital Communications', 
		'Digital Communications and Networking', 
		'Digital Electronics', 
		'Digital Electronics and Communication', 
		'Digital Electronics and Communication', 
		'Engineering', 
		'Digital Electronics and Communication Systems', 
		'Digital Electronics Engineering', 
		'Digital Image Processing', 
		'Digital Instrumentation', 
		'Digital Signal Processing', 
		'Digital Systems', 
		'Digital Systems and Communications', 
		'Engineering', 
		'Digital Systems and Computer Electronics', 
		'Digital Techniques and instrumentation', 
		'Distributed and Mobile Computing', 
		'Distributed Computing Systems', 
		'Distributed Systems', 
		'Drugs and Pharmaceuticals', 
		'Dyestuff Technology', 
		'Earthquake Engineering', 
		'E-Learning Technologies', 
		'Electric Power System', 
		'Electrical and Electronics (Power System)', 
		'Electrical and Electronics Engineering', 
		'Electrical and Mechanical Engineering', 
		'Electrical and Power Engineering', 
		'Electrical Devices and Power Systems', 
		'Electrical Drives and Control', 
		'Electrical Energy Systems', 
		'Electrical Engineering', 
		'Electrical Engineering (Electronics and Power)', 
		'Electrical   Engineering   (Instrumentation   and', 
		'Control)', 
		'Electrical instrumentation and Control', 
		'Engineering', 
		'Electrical Machines', 
		'Electrical Machines and Drives', 
		'Electrical Power Engineering', 
		'Electrical Power System', 
		'Electronic Circuits and System Design', 
		'Electronic Engineering', 
		'Electronic instrumentation and Control', 
		'Engineering', 
		'Electronics and Communication', 
		'(Communication System Engineering)', 
		'Electronics and Communication (Signal', 
		'Processing and Communication)', 
		'Electronics and Communication (Signal', 
		'Processing and VLSI Technology)', 
		'Electronics and Communication (VLSI Design)', 
		'Electronics  and  Communication  (VLSI  System', 
		'Design)', 
		'Electronics and Communication (Wireless', 
		'Communication Systems and Networks)', 
		'Electronics and Communication (Wireless', 
		'Communication Technology)', 
		'Electronics and Communication Engineering', 
		'Electronics  and  Communication  Engineering', 
		'(Industry integrated)', 
		'Electronics and Electrical Technology', 
		'Electronics and instrumentation Engineering', 
		'Electronics and Tele-Communication', 
		'Engineering', 
		'Electronics and Telecommunication Engineering', 
		'(Radio and System)', 
		'Electronics and Telecommunication Engineering', 
		'(Technologynician Electronic Radio)', 
		'Electronics and Telecommunications', 
		'Engineering', 
		'Electronics Communication and', 
		'instrumentation Engineering', 
		'Electronics Design and Technology', 
		'Electronics Design Technology', 
		'Electronics Engineering', 
		'Electronics Product Design and Technology', 
		'Electronics Systems and Communication', 
		'Electronics Technology', 
		'Electronics Tele Communication', 
		'Embedded and Real Time Systems', 
		'Embedded Control and Automation', 
		'Embedded Control Systems', 
		'Embedded System and Computing', 
		'Embedded System and VLSI', 
		'Embedded System and VLSI Design', 
		'Embedded Systems', 
		'Embedded Systems Technologies', 
		'Energetic Materials and Polymers', 
		'Energy and Environmental Engineering', 
		'Energy and Environmental Management', 
		'Energy Engineering', 
		'Energy Management', 
		'Energy Science and Technology', 
		'Energy Systems', 
		'Energy Systems Analysis and Design', 
		'Energy Systems and Management', 
		'Energy Systems Engineering', 
		'Energy Technology', 
		'Energy Technology and Management', 
		'Engineering Analysis and Design', 
		'Engineering and Management', 
		'Engineering Design', 
		'Engineering Education', 
		'Engineering Statistics', 
		'Environment and Water Resource Engineering', 
		'Environment Engineering', 
		'Environmental Biotechnology', 
		'Environmental Engineering', 
		'Environmental Engineering and Management', 
		'Environmental Management', 
		'Environmental Science and Engineering', 
		'Environmental Science and Technology', 
		'E-Security', 
		'Farm Machinery', 
		'Fashion and Apparel Engineering', 
		'Fashion Technology', 
		'Financial Engineering', 
		'Food Biotechnology', 
		'Food Engineering and Technology', 
		'Food Plant Operations Management', 
		'Food Process Engineering and Management', 
		'Food Processing Technology', 
		'Food Safety and Quality Management', 
		'Food Supply Chain Management', 
		'Food Technology', 
		'Food Technology and Management', 
		'Footwear Science and Engineering', 
		'Foundation Engineering', 
		'Foundry and Forge Technology', 
		'Fracture Mechanics', 
		'Fuel and Combustion', 
		'Future Studies and Planning', 
		'Gas Turbine Technology', 
		'Geo Informatics', 
		'Geoinformatics and Earth Observation', 
		'Geo Informatics and Surveying Technology', 
		'Geomachines and Structures', 
		'Geomechanics and Structures', 
		'Geotechnical and Geoenvironmental Energy', 
		'Geotechnical Earthquake Engineering', 
		'Geotechnical Engineering', 
		'Geotechnology', 
		'Green Energy Technology', 
		'Green Technology', 
		'Guidance and Navigation Control', 
		'Guided Missiles', 
		'Health Science and Water Engineering', 
		'Heat and Power', 
		'Heat Power and Thermal Engineering', 
		'Heat Power Engineering', 
		'Heat Ventilation and Air Conditioning', 
		'High Voltage and Power Systems Engineering', 
		'High Voltage Engineering', 
		'Highway Engineering', 
		'Highway Technology', 
		'Hill Area Development Engineering', 
		'Hydraulics and Flood Control', 
		'Hydraulics Engineering', 
		'Hydrology and Water Resources Engineering', 
		'Industrial Intelligent Systems', 
		'I.T. (Courseware Engineering)', 
		'Illumination Engineering', 
		'Illumination Technology and Design', 
		'Image Processing', 
		'Industrial and Production Engineering', 
		'Industrial Automation and RF Engineering', 
		'Industrial Automation and Robotics', 
		'Industrial Biotechnology', 
		'Industrial Catalysis', 
		'Industrial Design', 
		'Industrial Drives and Control', 
		'Industrial Electronics', 
		'Industrial Engineering', 
		'Industrial Engineering and Management', 
		'Industrial Instrumentation and Control', 
		'Industrial Mathematics', 
		'Industrial Metallurgy', 
		'Industrial Pollution Control', 
		'Industrial Power Control and Drives', 
		'Industrial Refrigeration and Cryogenics', 
		'Industrial Safety', 
		'Industrial Safety and Engineering', 
		'Industrial Structures', 
		'Industrial System and Drives', 
		'Industrial Systems Engineering', 
		'Information and Communication Technology', 
		'Information Engineering', 
		'Information Science and Technology', 
		'Information Security', 
		'Information Security Management', 
		'Information Systems', 
		'Information Technology', 
		'Information Technology (Artificial Intelligence', 
		'and Robotics)', 
		'Information Technology (Information and', 
		'Cyber Warfare)', 
		'Information Technology (Multimedia)', 
		'Information Technology and Engineering', 
		'Infrastructure Engineering', 
		'Infrastructure Engineering and Management', 
		'Infrastructure Engineering and Technology', 
		'Infrastructure Management', 
		'Instrumentation and Control (Applied', 
		'Instrumentation)', 
		'Instrumentation and Control Engineering', 
		'Instrumentation and Electronics', 
		'Instrumentation Engineering', 
		'Instrumentation Technology', 
		'Integrated Circuits Technology', 
		'Integrated Power Systems', 
		'Integrated Water Resources Management', 
		'Intelligent Systems', 
		'Internal Combustion and Automobiles', 
		'Internal Combustion Engineering', 
		'Internal Combustion Engines and Turbo', 
		'Machinery', 
		'Internet of Things', 
		'Iot and Sensor Systems', 
		'Irrigation and Drainage Engineering', 
		'Irrigation Engineering', 
		'Irrigation Water Management', 
		'Laser and Electro Optics', 
		'Laser Technology', 
		'Lean Manufacturing Engineering', 
		'Leather Technology', 
		'Machine Design', 
		'Machine Design and Robotics', 
		'Maintenance Engineering', 
		'Man-Made Textile Technology', 
		'Manufacturing and Automation', 
		'Manufacturing Engineering', 
		'Manufacturing Engineering and Automation', 
		'Manufacturing Engineering and Management', 
		'Manufacturing Engineering and Technology', 
		'Manufacturing Process', 
		'Manufacturing Process and Automation', 
		'Engineering', 
		'Manufacturing Science and Engineering', 
		'Manufacturing Systems and Management', 
		'Manufacturing Systems Engineering', 
		'Manufacturing Technology', 
		'Manufacturing Technology and Automation', 
		'Marine Engineering', 
		'Marine Technology', 
		'Material Engineering', 
		'Material Engineering (Nanotechnology)', 
		'Material Handling', 
		'Material Science and Chemical Technology', 
		'Material Science and Engineering', 
		'Material Science and Technology', 
		'Materials Engineering', 
		'Measurement and Control', 
		'Mechanical (Computer Aided Design', 
		'Manufacture and Engineering)', 
		'Mechanical (Computer integrated', 
		'Manufacturing)', 
		'Mechanical   (I.C.   Engine   and   Automobile', 
		'Engineering)', 
		'Mechanical and Automation Engineering', 
		'Mechanical and Materials Technology', 
		'Mechanical Engineering', 
		'Mechanical Engineering (CAD/CAM)', 
		'Mechanical Engineering (Cyber Physical', 
		'Systems)', 
		'Mechanical  Engineering  (Energy  System  and', 
		'Management)', 
		'Mechanical Engineering (Industry Integrated)', 
		'Mechanical Engineering (Manufacturing', 
		'Technology)', 
		'Mechanical Engineering (Production)', 
		'Mechanical Engineering (Thermal Engineering)', 
		'Mechanical Engineering Automobile', 
		'Mechanical Engineering Design', 
		'Mechanical Engineering Production', 
		'Mechanical Engineering (CAD)', 
		'Mechanical  Engineering-Product  Design  and', 
		'Development', 
		'Mechanical- Product Life Cycle Management', 
		'Mechanical System Design', 
		'Mechanical Welding and Sheet Metal', 
		'Engineering', 
		'Mechanical-Manufacturing Engineering', 
		'Mechatronics', 
		'Medical Electronics', 
		'Metallurgical and Materials Engineering', 
		'Metallurgical Engineering', 
		'Metallurgy', 
		'Metallurgy and Material Technology', 
		'Micro and Nano Electronics', 
		'Micro Electronics', 
		'Micro Electronics and Control Systems', 
		'Micro Electronics and VLSI Design', 
		'Micro Electronics and VLSI Technology', 
		'Micro Electronics Engineering', 
		'Microelectronics and VLSI Design', 
		'Microwave and Communication Engineering', 
		'Microwave and Millimeter Engineering', 
		'Microwave and Optical Communication', 
		'Microwave and Radar Engineering', 
		'Microwave and TV Engineering', 
		'Microwave Engineering', 
		'Microwaves', 
		'Mining Engineering', 
		'Mobile Communication and Network', 
		'Technology', 
		'Mobile Computing', 
		'Mobile Computing Technology', 
		'Mobile Technology', 
		'Modeling and Simulation', 
		'Modern Communication Engineering', 
		'Multimedia and Software Engineering', 
		'Multimedia Technology', 
		'Nano Science and Technology', 
		'Nano Technology', 
		'Network Engineering', 
		'Network infrastructure Management', 
		'Network Security and Management', 
		'Networking', 
		'Networking and internet Engineering', 
		'Neural Networks', 
		'New Material Process and Technology', 
		'Non-Sewered Sanitation', 
		'Nuclear Engineering', 
		'Nuclear Science and Technology', 
		'Ocean Technology', 
		'Oil Technology', 
		'Oils', 'Oleochemicals and Surfactants Technology', 
		'Optical Engineering', 
		'Optics and Optoelectronics', 
		'Opto Electronics and Communication Systems', 
		'Optoelectronics and Communication', 
		'Optoelectronics and Laser Technology', 
		'Opto-Electronics Engineering', 
		'Optoelectronics -Optical Communication', 
		'Packaging Technology', 
		'Paint Technology', 
		'Parallel Distributed Systems', 
		'Perfumery and Flavour Technology', 
		'Pervasive Computing Technology', 
		'Petrochem and Petroleum Refinery Engineering', 
		'Petrochemical Engineering', 
		'Petrochemical Technology', 
		'Petroleum Engineering', 
		'Petroleum Refining and Petrochemicals', 
		'Petroleum Technology', 
		'Pharmaceutical Biotechnology', 
		'Pharmaceuticals and Fine Chemical Technology', 
		'Pharmaceuticals Chemistry and Technology', 
		'Physical Metallurgy', 
		'Plant Design', 
		'Plastic Engineering', 
		'Plastics Engineering', 
		'Plastics Processing and Testing', 
		'Plastics Technology', 
		'Polymer Engineering', 
		'Polymer Nanotechnology', 
		'Polymer Science and Engineering', 
		'Polymer Science and Technology', 
		'Polymer Technology', 
		'Power and Energy Engineering', 
		'Power and Energy System', 
		'Power and Industrial Drives', 
		'Power Control and Drives', 
		'Power Electronics', 
		'Power Electronics and Control', 
		'Power Electronics and Drives', 
		'Power   Electronics   and   Drives   in  Electrical', 
		'Engineering', 
		'Power Electronics and Electrical Drives', 
		'Power Electronics and Machine Drives', 
		'Power Electronics and Power Systems', 
		'Power Electronics and Systems', 
		'Power Electronics Engineering', 
		'Power Engineering', 
		'Power Engineering and Energy Systems', 
		'Power Plant Engineering and Energy', 
		'Management', 
		'Power System and Control', 
		'Power System and Control Automation', 
		'Power System Control and Automation', 
		'Power System with Emphasis H. V. Engineering', 
		'Power Systems', 
		'Power Systems and Automation', 
		'Power Systems and Power Electronics', 
		'Power Systems and Renewable Energy', 
		'Power Systems Control and Automation', 
		'Engineering', 
		'Power Systems Engineering', 
		'Pre Stressed Concrete', 
		'Printing Engineering and Graphics', 
		'Communication', 
		'Printing Technology', 
		'Process and Food Engineering', 
		'Process Control', 
		'Process Control instrumentation', 
		'Process Dynamics and Control', 
		'Process instrumentation', 
		'Process Metallurgy', 
		'Product Design', 
		'Product Design and Commerce', 
		'Product Design and Development', 
		'Product Design and Manufacturing', 
		'Production and Industrial Engineering', 
		'Production Design and Manufacturing', 
		'Production Engineering', 
		'Production Engineering and Engineering Design', 
		'Production Engineering System Technology', 
		'Production Management', 
		'Production Technology', 
		'Production Technology and Management', 
		'Project Management', 
		'Propulsion Engineering', 
		'Public Health Engineering', 
		'Quality Engineering and Management', 
		'Radar and Communication', 
		'Radio Frequency and Microwave Engineering', 
		'Radio Physics and Electronics', 
		'Refrigeration and Air Conditioning', 
		'Reliability Engineering', 
		'Remote Sensing', 
		'Remote Sensing and GIS', 
		'Remote Sensing and Wireless Sensor Networks', 
		'Renewable Energy', 
		'Robotics and Automation', 
		'Robotics and Mechatronics', 
		'Rocket Propulsion', 
		'Rubber Technology', 
		'Rural Technology', 
		'Science in Software Engineering', 
		'Scientific Computing', 
		'Seismic Design and Earthquake Engineering', 
		'Sensor Technology', 
		'Signal Processing', 
		'Signal Processing and Communications', 
		'Signal Processing and Embedded Systems', 
		'Smart Sensing Communication and Networking', 
		'Technologies', 
		'Software Engineering', 
		'Software Systems', 
		'Soil and Water Conservation Engineering', 
		'Soil Mechanics', 
		'Soil Mechanics and Foundation Engineering', 
		'Solar Energy', 
		'Solar Power Systems', 
		'Spatial information Technology', 
		'Sports Technology', 
		'Structural and Construction Engineering', 
		'Structural and Foundation Engineering', 
		'Structural Design', 
		'Structural Dynamics and Earthquake', 
		'Engineering', 
		'Structural Engineering', 
		'Structural Engineering and Construction', 
		'Structural Engineering and Construction', 
		'Management', 
		'Surface Coating Technology', 
		'System and Network Security', 
		'System Management', 
		'System Software', 
		'Systems and Signal Processing', 
		'Technical Textile', 
		'Technology Management', 
		'Telecommunication Engineering', 
		'Telematics', 
		'Textile Chemistry', 
		'Textile Engineering', 
		'Textile Processing', 
		'Textile Processing Technology', 
		'Textile Technology', 
		'Textile Technology (Design and Manufacturing)', 
		'Thermal and Fluid Engineering', 
		'Thermal Engineering', 
		'Thermal  Engineering  (Refrigeration  and  Air', 
		'Conditioning)', 
		'Thermal Power Engineering', 
		'Thermal Science Engineering', 
		'Thermal Sciences and Energy Systems', 
		'Thermal Systems and Design', 
		'Tool Design', 
		'Tool Engineering', 
		'Town and Country Planning', 
		'Traffic and Transporting Engineering', 
		'Transport Science and Technology', 
		'Transportation Engineering', 
		'Translational Engineering', 
		'Transportation Engineering and Management', 
		'Transportation System Engineering', 
		'Tribology and Maintenance', 
		'Turbo Machinery', 
		'Urban Engineering', 
		'Virtual Prototyping and Digital Manufacturing', 
		'VLSI', 
		'VLSI and Embedded Systems', 
		'VLSI and Embedded Systems Design', 
		'VLSI and Microelectronics', 
		'VLSI Design', 
		'VLSI Design and Embedded Systems', 
		'VLSI Design and Signal Processing', 
		'VLSI Design and Testing', 
		'VLSI System Design', 
		'VLSI Systems', 
		'Waste Water Management', 'Health and Safety', 
		'Engineering', 
		'Water and Environmental Technology', 
		'Water Engineering and Management', 
		'Water Resource Engineering', 
		'Water Resource Management', 
		'Water Resources and Environmental', 
		'Engineering', 
		'Water Resources and Hydraulic Engineering', 
		'Water Resources and Hydro informatics', 
		'Weapons Engineering', 
		'Web Technologies', 
		'Wired and Wireless Communication', 
		'Wireless and Mobile Communications', 
		'Wireless Communication and Computing', 
		'Wireless Communication Technology', 
		'Wireless Communications', 
		'Wireless Networks and Applications', 
		'Wireless Technology',
		'Industrial Pharmacy', 
		'Pharmaceutical Analysis', 
		'Pharmaceutical Biotechnology', 
		'Pharmaceutical Chemistry', 
		'Pharmaceutical Quality Assurance', 
		'Pharmaceutical Technology', 
		'Pharmaceutics', 
		'Pharmacognosy', 
		'Pharmacology', 
		'Pharmacy Practice', 
		'Phytopharmacy and Phytomedicine', 
		'Regulatory Affairs',
		'Architecture Assistantship',
		'Interior Design',
		'Advanced Architecture', 
		'Advanced Design', 
		'Architectural and Construction Project', 
		'Management', 
		'Architectural Conservation', 
		'Architectural Design', 
		'Architecture and Settlement Conservation', 
		'Architecture Education', 
		'Building Management', 
		'Built Heritage', 
		'City Design', 
		'Computer Application', 
		'Construction Management', 
		'Energy Efficient and Sustainable Architecture', 
		'Environmental Architecture', 
		'Habitat Design', 
		'Housing', 
		'Interior Architecture', 
		'Interior Design', 
		'Landscape Architecture', 
		'Project Management', 
		'Real Estate Development', 
		'Sustainable Architecture', 
		'Theory and Design', 
		'Urban Conservation', 
		'Urban Design', 
		'Urban Design and Development',
		'City and Regional Planning and Management', 
		'City Planning', 
		'City Planning and Management', 
		'Community Planning', 
		'Conservation Planning', 
		'Environmental Planning', 
		'Environmental Planning and Management', 
		'Housing', 
		'Industrial Area Planning and Management', 
		'Infrastructure Planning', 
		'Infrastructure Planning and Management', 
		'Land-Use Planning', 
		'Regional and Rural Development Planning', 
		'Regional Planning', 
		'Rural Planning and Development', 
		'Rural Planning and Management', 
		'Town and Country Planning', 
		'Town Planning', 
		'Transport Planning and Management', 
		'Transportation Planning', 
		'Urban and Regional Planning', 
		'Urban and Rural Planning', 
		'Urban Design', 
		'Urban Development', 
		'Urban Planning',
		'Apparel Design and Fabrication Technology', 
		'Apparel Design and Fashion Technology', 
		'Art for Drawing Teacher', 
		'Beauty and Hair Dressing', 
		'Beauty Culture', 
		'Beauty Culture and Cosmetology', 
		'Commercial Art', 
		'Cosmetology', 
		'Costume Design and Dress Making', 
		'Costume Design and Garment Technology', 
		'Craft Technology', 
		'Fashion and Apparel Design', 
		'Fashion Design and Garment Technology', 
		'Fashion Designing', 
		'Fashion Technology', 
		'Fine Arts', 
		'Garment Technology', 
		'Home Science', 
		'Interior Decoration', 
		'Interior Design', 
		'Textile Design', 
		'Textile Designing', 
		'Travel and Tourism',
		'Accessory Design', 
		'Animation', 
		'Applied Arts', 
		'Applied Arts and Crafts (Fashion and Apparel', 
		'Design)', 
		'AR and CR for Films', 
		'Audiography', 
		'Cinematography', 
		'Commercial Art', 
		'Digital Imaging', 
		'Fashion and Apparel Design', 
		'Film and Media', 
		'Film and Television', 
		'Film Direction', 
		'Film Editing', 
		'Fine Arts', 
		'Fine Art (Sculpture)', 
		'Fine Art (Animation)', 
		'Fine Art (Ceramics)', 
		'Fine Art (Metal Craft)', 
		'Fine Art (Photography)', 
		'Media Production Management', 
		'Painting', 
		'Product Design', 
		'Screen Acting', 
		'Script Writing', 
		'Sound Recording and Sound Design', 
		'Television', 
		'Textile Design', 
		'Visual Effects',
		'Advertisement and Public Relation', 
		'Applied Arts', 
		'Applied Art (Visual Communication Design)', 
		'Applied Art (Communication Design)', 
		'Applied Art (Illustration)', 
		'Customer Service Management', 
		'Direction', 
		'Electronic Cinematography', 
		'Fashion Technology', 
		'Feature Film Screenplay Writing', 
		'Film Archiving', 
		'Film Studies', 
		'Fine Art (Painting)', 
		'Fine Art (Mural)', 
		'Fine Art (Sculpture)', 
		'Fine Art (Photography and Media', 
		'Communication)', 
		'Fine Arts',
		'information techology', 
		'computer science', 
		'physics chemistry', 
		'maths', 
		'botany', 
		'zoology', 
		'microbiology', 
		'biotechnology', 
		'geology', 
		'electronics'
        ]
    autocomplete(document.getElementById("institute"), countries);
</script>

</body>

</html> 